# Site settings
title: 'CS373 Spring 2016: Darragh Murphy'
description: 'My blog for my software engineering class'
#url: 'http://dazmurphy.github.io'
baseurl: '/cs373-blog/'
google_analytics: 'UA-72888152-2'

author:
  name: 'Darragh Murphy'
  github_username: Dazmurphy
  linkedin_username:  Dazmurphy

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
